// Server-only SkyPilot task.yaml generator.
// Emits a manifest pinned to our golden mining image with production-tuned env.

export interface SkyPilotTaskInput {
  /** Operator wallet address — injected as USER_WALLET. */
  userWallet: string;
  /** Optional override of cluster name (SkyPilot CLI -c). */
  clusterName?: string;
  /** Number of GPUs per node. Defaults to 1. */
  gpusPerNode?: number;
  /** Optional explicit allow-list. Defaults to ≥16GB-VRAM NVIDIA accelerators. */
  accelerators?: string[];
  /** Optional cloud restriction (e.g. ["aws","gcp"]). */
  clouds?: string[];
  /** Disk size GB. Defaults to 80. */
  diskGb?: number;
}

// ≥ 16GB VRAM NVIDIA GPUs that SkyPilot understands by name.
const DEFAULT_HIGH_VRAM_GPUS = [
  "A10",
  "A10G",
  "L4",
  "A100",
  "A100-80GB",
  "H100",
  "H100-80GB",
  "L40",
  "L40S",
  "A6000",
];

const GOLDEN_IMAGE = "arcagrid/btx-oneclick-miner:latest";

function yamlEscape(value: string) {
  if (/^[A-Za-z0-9_\-./:=]+$/.test(value)) return value;
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * Generates a SkyPilot task.yaml manifest string for an ArcaGrid mining job.
 * The manifest exclusively targets NVIDIA GPUs with ≥16GB VRAM and injects
 * the production-verified env block.
 */
export function generateSkyPilotTaskYaml(input: SkyPilotTaskInput): string {
  const gpus = input.gpusPerNode ?? 1;
  const accelerators = (input.accelerators ?? DEFAULT_HIGH_VRAM_GPUS).map(
    (g) => `${g}:${gpus}`,
  );
  const disk = input.diskGb ?? 80;

  const cloudsBlock =
    input.clouds && input.clouds.length > 0
      ? `  any_of:\n${input.clouds.map((c) => `    - cloud: ${c}\n      accelerators: {${accelerators.map((a) => yamlEscape(a)).join(", ")}}`).join("\n")}\n`
      : `  accelerators: {${accelerators.map((a) => yamlEscape(a)).join(", ")}}\n  disk_size: ${disk}\n  # min VRAM: 16 GB (NVIDIA only)\n`;

  const envBlock = [
    `  USER_WALLET: ${yamlEscape(input.userWallet)}`,
    `  BTX_MINING_MODE: pool`,
    `  BTX_MINE_BATCH_SIZE: "20"`,
    `  BTX_MATMUL_SOLVE_BATCH_SIZE: "4"`,
  ].join("\n");

  const name = input.clusterName ?? "arcagrid-btx-worker";

  return [
    `# Generated by ArcaGrid — do not edit by hand.`,
    `name: ${yamlEscape(name)}`,
    ``,
    `resources:`,
    cloudsBlock.trimEnd(),
    ``,
    `envs:`,
    envBlock,
    ``,
    `# Pinned golden image — production-verified worker runtime.`,
    `image_id: docker:${GOLDEN_IMAGE}`,
    ``,
    `run: |`,
    `  echo "[arcagrid] booting worker for $USER_WALLET"`,
    `  exec /opt/arcagrid/entrypoint.sh`,
    ``,
  ].join("\n");
}